In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msg
import string
import re
import nltk

In [3]:
df = pd.read_csv("data_preprocess.csv")
df.describe()

                                            OriginalTweet Sentiment
count                                                2999      2999
unique                                               2995         3
top     cac urge elderly stock food stay home amid cor...  Negative
freq                                                    2      1315

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
text_data = np.array(df["OriginalTweet"])
vectorizer = TfidfVectorizer(min_df = 2) #Garrantzitzua, zein den hitzen agerpen minimoa kontuan hartzeko.
train_bow = vectorizer.fit_transform(text_data)
print("Matrizearen tamaina TF-IDF aplikatu ondoren : ",train_bow.shape) #Modu honetan badakigu zenbat atributu ditugu.

Matrizearen tamaina TF-IDF aplikatu ondoren :  (2999, 3909)

In [5]:
df_tf = pd.DataFrame(train_bow.todense(), columns=vectorizer.get_feature_names())
df_tf["Sentiment"] = df["Sentiment"] #Taula sortu atributu berriekin

In [6]:
df_tf.describe()

,abc,ability,able,about,above,abroad,absolute,absolutely,abundance,abuse,...,younger,yours,yourself,youself,youtube,yr,zero,zinc,zombie,zombieapocalypse
count,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,...,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000
mean,0.000410,0.001306,0.003187,0.000838,0.000192,0.000288,0.000580,0.000891,0.000271,0.000184,...,0.000416,0.000196,0.000228,0.000226,0.000714,0.000275,0.000399,0.000296,0.000925,0.000494
std,0.010155,0.018080,0.027425,0.016087,0.007425,0.009178,0.013067,0.016472,0.008570,0.007134,...,0.011550,0.007588,0.008837,0.008817,0.017048,0.010851,0.010932,0.008114,0.015547,0.013941
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.293542,0.346682,0.495880,0.520298,0.298966,0.338795,0.331872,0.419799,0.278845,0.278031,...,0.402505,0.295282,0.351483,0.374930,0.609661,0.491000,0.324962,0.229747,0.374956,0.492972

In [7]:
df = pd.read_csv("data_preprocess.csv")
STOPWORDS = set(stopwords.words('english'))
STOPWORDS.add('u') #Konponketa 'u' hitza kontuan ez izateko.
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in set(STOPWORDS)])

df["OriginalTweet"] = df["OriginalTweet"].apply(lambda text:remove_stopwords(text))
df['OriginalTweet'] = df['OriginalTweet'].replace({'couid': 'covid'}, regex=True) #Hitza txarto eraldatua
df['OriginalTweet'] = df['OriginalTweet'].replace({'amp': ' '}, regex=True) #& arazoak

NameError: name 'stopwords' is not defined

In [8]:
from sklearn.model_selection import train_test_split
df_tf.index
df_tf['Sentiment'] = df_tf['Sentiment'].replace(['Negative'],0.0)
df_tf['Sentiment'] = df_tf['Sentiment'].replace(['Neutral'],1.0)
df_tf['Sentiment'] = df_tf['Sentiment'].replace(['Positive'],2.0)

In [9]:
X = df_tf.drop('Sentiment', axis=1).values
y = df_tf['Sentiment']

In [29]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=3)

In [25]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [26]:
y_train.shape

(2998,)

In [30]:
poly = PolynomialFeatures(degree = 4, interaction_only=False, include_bias=False)
X_poly = poly.fit_transform(X_train)
X_poly.shape

KeyboardInterrupt: